default: # default connection
    # connection: default
    type: "mysql"
    host: "localhost"
    port: 8889
    username: "root"
    password: "root"
    database: "api_borne"
    entities: [
        "../Models/Company.ts",
        Ingredient,
        Order,
        OrderHasProduct,
        Product,
        ProductHasIngredient,
        Role,
        Stock,
        User,
        State
    ]
    synchronize: true,
    logging: false

    # make connection with all the entity
    # entities: ["src/Models/*.ts"]
    # entities: [join(__dirname, 'Models', '*.{ts,js}')]
    # entities: ['../Models/*.ts']
